language: perl
perl:
  - "5.18"

before_install:
  - cpanm Carton
  - git submodule update --init --recursive
  - git clone --recursive git://github.com/maxmind/libmaxminddb
  - cd libmaxminddb
  - ./bootstrap
  - ./configure
  - make
  - sudo make install
  - sudo ldconfig
  - cd ..
  - sudo apt-get update
  - sudo apt-get install --assume-yes apache2-mpm-prefork apache2.2-bin apache2.2-common apache2-prefork-dev apache2-utils
  - git clone git://github.com/ttkzw/mod_remoteip-httpd22
  - cd mod_remoteip-httpd22
  - sudo apxs2 -i -c -n mod_remoteip.so mod_remoteip.c
  - cd ..
  - ./bootstrap
  - CFLAGS="-std=gnu99 -Wall -Wextra -Werror -Wno-missing-field-initializers" ./configure
  - make
  - sudo make install

install:
  - cpanm --installdeps --notest .

script:
  - perl Makefile.PL -configure -httpd_conf t/setup/apache2.conf -src_dir /usr/lib/apache2/modules
  - ./t/TEST -v

after_failure:
  - sudo apache2ctl -M
  - cat t/logs/error_log

notifications:
  email:
    recipients:
      - dev@maxmind.com
    on_success: change
    on_failure: always

env:
  global:
   - secure: "SaZg9Tde8fwrRST4ik3S5isIRqevV49UiIpwyiAO5R7EBS3QrARGrAV3HUpkWPI+tvPFW98+WoC+CesX2rEV2mXRW8+7H+9sRcfDCQFzxQw0yUh/qjJjC/XSZNYb67LiP9Je8fSSpZfta4gn7MvJy4koFZlP/BKloVqUvxjydmk="

addons:
  coverity_scan:
    project:
      name: "maxmind/mod_maxminddb"
      description: "Apache module for libmaxminddb"
    notification_email: dev@maxmind.com
    build_command_prepend: "make clean"
    build_command:   "make"
    branch_pattern: coverity_scan
